version: '3.7'

services:
  web:
    build: ./btre_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./btre_project/:/usr/src/btre/
    ports:
      - 8000:8000
    env_file:
      - btre_project/btre/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - btre_project/btre/.env.dev

volumes:
  postgres_data: