version: '3.7'

services:
  web:
    build: yukiumetsudock/btre_django_web
    command: gunicorn django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./btre_project/:/usr/src/btre/
    ports:
      - 8000:8000
    env_file:
      - btre_project/btre/.env.prod
    depends_on:
      - db

  nginx:
    build: yukiumetsudock/btre_nginx
    ports:
      - 1337:80
    volumes:
      - ./btre_project/:/usr/src/btre/
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    # this ports config is for pgadmin
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - btre_project/btre/.env.prod

volumes:
  postgres_data:
  btre: